name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (using Node.js 20)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Maintain Python version for your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # No need for poetry env use as pyproject.toml likely defines dependencies

      - name: Install project dependencies
        run: |
          poetry install

      # Removed the optional Build and test step (if applicable)

      - name: Create .env file securely  # Assuming GitHub Secrets are configured
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > SA_Bot\sabot\.env

      - name: Deploy to Streamlit (addressing execution order)
        run: |
          poetry run SA_Bot\sabot\SAbot.py && poetry run streamlit run SA_Bot\sabot\Visual.py
          # Consider using environment variables for configurations:
          # poetry run streamlit run SA_Bot\sabot\Visual.py --server.port $PORT
