name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Update poetry.lock if necessary
        run: |
          poetry lock --no-update

      - name: Install project dependencies without installing the current project
        run: |
          poetry install --no-root

      - name: Create .env file securely
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          New-Item -ItemType Directory -Force -Path SA_Bot\sabot
          Add-Content SA_Bot\sabot\.env "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
          Add-Content SA_Bot\sabot\.env "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}"

      - name: Verify Environment Variables
        run: |
          echo "OPENAI_API_KEY: $env:OPENAI_API_KEY"
          echo "HUGGINGFACE_API_KEY: $env:HUGGINGFACE_API_KEY"

      - name: Run SAbot.py (setup tasks)
        run: |
          poetry run python SA_Bot\sabot\SAbot.py

      - name: Start Streamlit in background
        run: |
          poetry run streamlit run SA_Bot\sabot\Visual.py --server.headless true &
      
      - name: Wait for 2 minutes
        run: |
          Start-Sleep -Seconds 120  # Sleep for 2 minutes (120 seconds)

      - name: List Running Processes
        run: |
          Get-Process

      - name: Stop Streamlit
        run: |
          Get-Process -Name streamlit -ErrorAction SilentlyContinue | Stop-Process
