name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies without installing the current project
        run: |
          poetry install --no-root

      - name: Create .env file securely
        run: |
          New-Item -ItemType Directory -Force -Path SA_Bot\sabot
          Add-Content SA_Bot\sabot\.env "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
          Add-Content SA_Bot\sabot\.env "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}"

      - name: Run SAbot.py (setup tasks)
        run: |
          poetry run python SA_Bot\sabot\SAbot.py

      - name: Debug Environment Variables
        run: |
          echo "OPENAI_API_KEY: $env:OPENAI_API_KEY"
          echo "HUGGINGFACE_API_KEY: $env:HUGGINGFACE_API_KEY"
          poetry run streamlit config show

      - name: Start Streamlit in background
        run: |
          Start-Process powershell -ArgumentList 'poetry run streamlit run SA_Bot\sabot\Visual.py --server.headless true' -NoNewWindow

      - name: Wait for 5 minutes
        run: |
          Start-Sleep -Seconds 300  # Sleep for 5 minutes (300 seconds)

      - name: Stop Streamlit
        run: |
          Get-Process -Name streamlit | Stop-Process
