name: Deploy to Streamlit Sharing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Generate requirements.txt
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Set up environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}" >> .env

      - name: Run SAbot.py (setup tasks)
        run: |
          poetry run python SA_Bot/sabot/SAbot.py

      - name: Start Streamlit in background
        run: |
          nohup poetry run streamlit run SA_Bot/sabot/Visual.py --server.headless true &

      - name: Wait for 10 minutes
        run: |
          sleep 600

      - name: Stop Streamlit
        run: |
          pkill -f streamlit
